In [1]:
#Pandas is a python library designed specifically for data manipulation, analysis, file handling and cleaning
import pandas as pd

In [2]:
#Reading CSV file using pandas libray through read_csv() function and assigning output to a variable for future refernce
dataset=pd.read_csv("Salary_Data.csv")

In [3]:
#printing the variable to know what is there in the CSV file
dataset

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [4]:
#Assigning particular column values (YearsExperience) into variable 'independent';
#Use double square brackets to get the individual column values into variable
independent=dataset[["YearsExperience"]]

#Printing the individual column values 
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [5]:
#Assigning particular column values (Salary) into variable 'dependent';
#Use double square brackets to get the individual column values into variable
dependent=dataset[["Salary"]]

#Printing the individual column values 
dependent

    Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [6]:
#sklearn is a open-source machine learning library for Python;
#It provides efficient procedure to split train set and test set data separately
#Using 'from', we can load specific functions (model_selection) into memory
from sklearn.model_selection import train_test_split

#X --> Input; Y--> Output
#X_train = input training set; X_test = input test set
#Y_train = output train set; Y_test = output test set
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.3, random_state=0)

#Printing input training set & output test set into the console
X_train,Y_test

(    YearsExperience
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,
     Salary
 2    37731
 28  122391
 13   57081
 10   63218
 26  116969
 24  109431
 27  112635
 11   55794
 17   83088)

In [7]:
#sklearn is a open-source machine learning library for Python;
#LinearRegression is ML based algoritham to perform regression task
#Using 'from', we can load specific functions (linear_model) into memory
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

#fit( ) method substitues the input values into model
#after fit( ) execution, weight(w) and bais (b) would be calculated
regressor.fit(X_train, Y_train)

LinearRegression()

In [8]:
#weight would be calculated in this ‘coef_’ variable
weight = regressor.coef_

#Printing weight into console
weight

array([[9360.26128619]])

In [9]:
#Bais is nothing but origin which is stored in ‘intercept_’ variable
bais = regressor.intercept_

#Printing bais into console
bais

array([26777.3913412])

In [10]:
y_pred = regressor.predict(X_test)

In [11]:
#sklearn is a open-source machine learning library for Python;
#r2_score is nothing but 'Coefficient of determination' also called R² score, is used to evaluate the performance of a linear regression model
#Using 'from', we can load specific functions (r2_score) into memory
from sklearn.metrics import r2_score

#r2_score is a regression score function
r_score = r2_score(Y_test,y_pred)

#Printing evaluated value (Good model --> nearly to 1; bad model --> nearly to 0 )
r_score

0.9740993407213511

In [12]:
#pickle is a built-in standard library used for serializing and deserializing Python object structures
import pickle

#creating file name to store the model for future reference
fileName = "finalized_model_linear.sav"

In [13]:
#dumping the model (regressor) into file Name to refer in other place
#wb --> write binary; sav --> file extension for saving moddel
pickle.dump(regressor, open(fileName,'wb'))

In [14]:
#loading the saved model with fileName 
#rb --> read binary
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))

In [15]:
#Testing the model by giving the real time input
result = loaded_model.predict([[15]])

#Printing the final result
result

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[167181.3106341]])